### ISSUE TITLE
Dictionary with Hubbard atoms to be perturbed as input to the UscfParallelizeAtomsWorkChain

### ISSUE THREAD

**Issue by ChRicca** [sphuber/aiida-quantumespresso-uscf#1]
For some applications, when using the `UscfParallelizeAtomsWorkCHain`, it will be useful have the option to provide a `hubbard_sites` dictionary with the atoms to be perturbed as input to the workchain instead of performing the initialization step in which the atoms are classified according to the symmetry

**Comment by sphuber** [comment]
If I remember correctly, you would want this functionality because for example in a structure with a defect, the symmetry is strongly reduced and the code would calculate `U` for each individual atom. However, you know that despite the broken symmetry groups of atoms can still in approximation be treated to have the same `U` term and so you only want to perform the calculation for a subset of the Hubbard sites, indicated by this dictionary `hubbard_sites`. Is this correct?

Is this is a correct representation of the problem, more information than just that `hubbard_sites` dictionary is required by the workchain though, because at the end of the individual `UscfCalculation` for each site, the final collection calculation would still expect all `pert` files for all Hubbard atoms to be in the output folder. This means that the workchain will have to duplicate these files for the sites that were not explicitly computed from those sites that were computed. In other words, the workchain would need to know to which computed sites the non-computed sites can be considered equivalent. Right?

**Comment by ChRicca** [comment]
Yes, I would like this functionality because independently from the symmetry detected by QE, Hubbard sites lying at the same distance from the defect are expected to have the same U value (distance from the defect sites or atomic occupations for each site printed in the pw.out when performing DFT+U calculations can be used as criterion to organize the Hubbard sites in group of equivalent atoms). This could reduce the number of Uscf calculation with respect to the case when symmetry is used to distinguish between different Hubbard sites.

So far I  can see are two possible cases:
1) non magnetic structures: imagine we have identified according to the distance from the defect 3 types Ti1, Ti2, Ti3,  we could run a Uscf  calculation for each type specifying in the Uscf input do_only_one(#number_of_one_of_the_Ti_atoms_corresponding_to_Ti1or2or3) and the we run a final Uscf calculation with collect=True and search_method=2 (this should take care of the missing pert files)

2) magnetic structures: imagine your system is AFM and you have types  6 types (sites at the same distance from the defect can be both spin up and spin down) Ti1_spinup  and Ti1_spindown, Ti2_spinup  and Ti2_spindown, Ti3_spinup  and Ti3_spindown, again we could run one Uscf for one of the Ti of type 1, one for Ti2 and one for Ti3.Finally,  we  do the Uscf collect calculation in which we use the    skip_type/ merge_type to skip (for example we skip Ti1_spindown and merge it with Ti1_spinup for which the chi matrices were computed in the previous step) and  search_method=2. So probably in this case we need the Hubbard_sites dictionary (which will have 6 entries) and we would need also a way to specify which atoms are at the same distance from the defect (so should have the same U) but have opposite spin.

**Comment by ChRicca** [comment]
Just to be sure I was clear, the default in the Uscf code is search_method =1 in which symmetry is used to check  inequivalent atoms. with search_method = 2, symmetry is not going to be applied, but the atoms will be distinguished according to the types specified in the pw.in file.
For reference, please look at  Uscf documentation in HUBBARD/Doc:
 var search_method   -type INTEGER {
                Method of searching for atoms to be perturbed.
                1 = Find how many inequivalent Hubbard atoms
                    there are (using symmetry). Atoms which have the
                    same type but are not equivalent by symmetry will
                    be distinguished in this case.
                2 = Find how many different types of Hubbard atoms there
                    are (no use of symmetry). Warning: atoms which
                    have the same type but which are inequivalent
                    by symmetry will not be distinguished in this case
                    (use option 1 instead).
             }

**Comment by sphuber** [comment]
I have updated the `UscfParallelizeAtomsWorkChain` to use the `UscfBaseWorkChain` workchain for the initialization step. This means that it will also use the `parameters` input node. This means that you can simply specify `search_method: 2` in the `parameters` node and everything will work just fine. I just tested this for the `SrTiO3` structure you sent me and I think the resulting behavior is what you were looking for. This would mean that we do not need any special inputs or changes to the workflow.

**Comment by sphuber** [comment]
This seems to be working by just explicitly setting `search_method: 2` in the `parameters` input node to the `HpCalculation`
